$ErrorActionPreference = 'Stop'
$env:MPLCONFIGDIR = Join-Path (Get-Location) '.matplotlib'

$env:SILVER_CLEAN_DF_PATH = 'silver_RRL_interpolate_extended_train.csv'
$env:SILVER_TARGET_COL = 'Silver_Futures'
$env:SILVER_DATE_COL = 'Date'
$env:SILVER_HORIZON = '1'
$env:SILVER_OUTER_TRAIN_RATIO = '0.88'
$env:SILVER_FINAL_VAL_RATIO = '0.10'
$env:SILVER_TUNING_SEED = '123'
$env:SILVER_REPORTS_DIR = 'reports/silver_train_only_retrained_v2'
$env:SILVER_SAVE_ROOT_DIR = 'models/silver_train_only_retrained_v2'
$env:SILVER_INIT_POINTS = '10'
$env:SILVER_N_ITER = '30'
$env:SILVER_MAX_EPOCHS_TUNING = '30'
$env:SILVER_MAX_EPOCHS_FINAL = '50'
$env:SILVER_EARLY_STOPPING_PATIENCE = '5'
$env:SILVER_EARLY_STOPPING_MIN_DELTA = '2e-5'
$env:SILVER_FINAL_SEEDS = '0,1,2,7,11,17,21,42,99,123'
$env:SILVER_LOOKBACK_RANGE = '12,24'
$env:SILVER_FILTERS_RANGE = '20,44'
$env:SILVER_KERNEL_SIZE_RANGE = '2,4'
$env:SILVER_LSTM_UNITS_RANGE = '96,144'
$env:SILVER_DENSE_UNITS_RANGE = '24,48'
$env:SILVER_DROPOUT_RANGE = '0.28,0.45'
$env:SILVER_LEARNING_RATE_RANGE = '0.00001,0.01'
$env:SILVER_L2_REG_RANGE = '0.00005,0.0005'
$env:SILVER_BATCH_SIZE_EXP_RANGE = '4,5'

& .\.venv\Scripts\python.exe train_silver_RRL_interpolate.py
