$ErrorActionPreference = 'Stop'
$env:MPLCONFIGDIR = Join-Path (Get-Location) '.matplotlib'

$env:GOLD_CLEAN_DF_PATH = 'df_gold_dataset_gepu_extended_train.csv'
$env:GOLD_TARGET_COL = 'Gold_Futures'
$env:GOLD_DATE_COL = 'Date'
$env:GOLD_HORIZON = '1'
$env:GOLD_OUTER_TRAIN_RATIO = '0.88'
$env:GOLD_FINAL_VAL_RATIO = '0.10'
$env:GOLD_TUNING_SEED = '123'
$env:GOLD_REPORTS_DIR = 'reports/gold_train_only_retrained_v2'
$env:GOLD_SAVE_ROOT_DIR = 'models/gold_train_only_retrained_v2'
$env:GOLD_INIT_POINTS = '10'
$env:GOLD_N_ITER = '30'
$env:GOLD_MAX_EPOCHS_TUNING = '30'
$env:GOLD_MAX_EPOCHS_FINAL = '50'
$env:GOLD_EARLY_STOPPING_PATIENCE = '5'
$env:GOLD_EARLY_STOPPING_MIN_DELTA = '2e-5'
$env:GOLD_FINAL_SEEDS = '0,1,2,7,11,17,21,42,99,123'
$env:GOLD_LOOKBACK_RANGE = '28,42'
$env:GOLD_FILTERS_RANGE = '24,48'
$env:GOLD_KERNEL_SIZE_RANGE = '2,4'
$env:GOLD_LSTM_UNITS_RANGE = '40,96'
$env:GOLD_DENSE_UNITS_RANGE = '24,40'
$env:GOLD_DROPOUT_RANGE = '0.30,0.48'
$env:GOLD_LEARNING_RATE_RANGE = '0.002,0.008'
$env:GOLD_L2_REG_RANGE = '0.0001,0.0008'
$env:GOLD_BATCH_SIZE_EXP_RANGE = '4,5'

& .\.venv\Scripts\python.exe train_gold_RRL_interpolate.py
